### ISSUE TITLE
Update oracle MAX_PRIORITY_FEE_PER_GAS env variable

### ISSUE THREAD

**Issue by karapetyantv** [mixbytes/lido-dot-ksm-oracle#53]
NAME: MAX_PRIORITY_FEE_PER_GAS

Network: Testnet
Cluster: DEV, PROD
UPDATE: 1000000000 -> 0

Network: Polkadot
Cluster: DEV, PROD
UPDATE: 1000000000 -> 10000000000

**Comment by markus24mxb** [comment]
https://github.com/mixbytes/lido-dot-ksm-oracle/commit/736ff068ef27f0d558e9151b3741481be02f1c6f
